"""empty message

Revision ID: cca39c7a863f
Revises: f35f1cbdb0ef
Create Date: 2018-02-13 14:36:56.477809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca39c7a863f'
down_revision = 'f35f1cbdb0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('level_name', sa.Text(), nullable=True))
    op.drop_column('event', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('event', 'level_name')
    # ### end Alembic commands ###
